= Changelog
:toc:
:toclevels: 2
:uri-keep-a-changelog: http://keepachangelog.com/en/1.0.0/
:uri-semver: http://semver.org/spec/v2.0.0.html

This document is based on thelink:{uri-keep-a-changelog}[Keep a Changelog 1.0.0 specification].

This project follows link:{uri-semver}[the semantic version 2.0 specification].

Each new should include:

* Version (semantic version)
* Date of release (in `yyyy/mm/dd` format)

For each release, a subsection should be added for each of the following if they are non-empty:

* `Added` for new features.
* `Changed` for changes in existing functionality.
* `Deprecated` for soon-to-be removed features.
* `Removed` for now removed features.
* `Fixed` for any bug fixes.
* `Security` in case of vulnerabilities.

== UNRELEASED

=== Changed

* *Breaking* - `GradleRunner.initScripts` type changed from `List<String>` to `List<Path>`
* `GradleRunner.buildScanEnabled` deprecated for removal and `GradleRunner.buildScan` added
* `GradleRunner.buildScanDisabled` deprecated for removal and `GradleRunner.noBuildScan` added
* `GradleRunner.buildCacheEnabled` deprecated for removal and `GradleRunner.buildCache` added
* `GradleRunner.buildCacheDisabled` deprecated for removal and `GradleRunner.noBuildCache` added

=== Added

* `FileContext.append(CharSequence, Charset)` method to append character sequence content to a file
* `FileContext.appendNewline(CharSequence, Charset)` method to append character sequence content to a file
* `FileContent.replaceEachLine(Charset, (lineNumber: Int, text: String) -> CharSequence)` method to conditionally replace content
* Indexed access for `BuildResult` for both outcome and task paths
** `BuildResult[":taskPath"]`, `BuildResult[":first", ":second"]`
** `BuildResult[TaskOutcome.SUCCESS]`
* Extension properties that may simplify or clarify assertions on `BuildTask`. For example:
** `BuildTask.success` is `true` when the outcome is `TaskOutcome.SUCCESS`
** `BuildTask.failed` is `true` when the outcome is `TaskOutcome.FAILED`
* More `GradleRunner` CLI options support:
** `rerunTasks` ⇒ `--rerun-tasks`
** `refreshDependencies` ⇒ `--refresh-dependencies`
** `refreshDependencies` ⇒ `--refresh-dependencies`
** `projectCacheDir` ⇒ `--project-cache-dir`
** `parallel` ⇒ `--parallel`
** `noParallel` ⇒ `--no-parallel`
** `maxWorkers` ⇒ `--max-workers`
** `settingsFile` ⇒ `--settings-file`
** `configureOnDemand` ⇒ `--configure-on-demand`
** `includedBuilds` ⇒ `--include-build`

== 0.2.1 (2017/12/13)

=== Fixed

* Published POM did not have a version specified.
  See link:https://github.com/mkobit/gradle-test-kotlin-extensions/issues/13[#13] and link:https://youtrack.jetbrains.com/issue/KT-21806[KT-21806].

== 0.2.0 (2017/12/06)

=== Deprecated

* `GradleRunner.buildWith` method in favor of added extensions
* `GradleRunner.buildAndFailWith` method in favor of added extensions
* `RunnerConfigurer` type

=== Changed

* Base package namespace of classes from `com.mkobit.gradle.test` to `com.mkobit.gradle.test.kotlin.testkit.runner`
* Kotlin upgraded from 1.1.60 to 1.2.0

=== Added

* `Automatic-Module-Name` of `com.mkobit.gradle.test.kotlin`
* `GradleRunner` file manipulation extensions (see README for example usage)
** `projectDirPath` - `Path?` to the project directory
** `setupProjectDir` method to configure the project directory
* `FileContext` types for simplifying manipulation and creating file system objects in the project directory
** `RegularFileContext` for dealing with regular files
** `DirectoryContext` for  managing a directory
** `FileAction` for different approaches to treating the files

== 0.1.0 (2017/10/27)

Initial release
